---
# Source: flame/templates/controller-job-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flame-controller-job-configmap
  namespace: default
data:
  Chart.yaml: |
    ---
    apiVersion: v1
    appVersion: "1.0"
    description: a helm chart for flame job
    name: flame-job
    version: 1.0

  values.yaml: |
    ---
    servicePort:
      agent: 10103

    endpoint:
      apiserver: https://example.apiserver.flame.test:443
      notifier: example.notifier.flame.test:443

    # enable this in case a selfsigned cert is in use (for test only)
    # this holds true in fiab setting
    insecure: true
  job-agent.yaml.mustache: |
    {{=<% %>=}}
    ---
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{ .Release.Namespace }}-agent-<% taskId %>
      namespace: {{ .Release.Namespace }}
    spec:
      template:
        # activeDeadlineSeconds: <% maxWaitTime %>
        # ttlSecondsAfterFinished: 180 # supported from v1.21
        spec:
          imagePullSecrets:
            - name: ecr-pull-secret
          containers:
            - args:
                - "--apiserver"
                - "{{ .Values.endpoint.apiserver }}"
                - "--notifier"
                - "{{ .Values.endpoint.notifier }}"
                {{ if .Values.insecure }}
                - "--insecure"
                {{ end }}
              command: ["/usr/bin/flamelet"]
              image: <% imageLoc %>
              imagePullPolicy: IfNotPresent
              name: {{ .Release.Namespace }}-agent-<% taskId %>
  
              ports:
                - containerPort: {{ .Values.servicePort.agent }}
  
              resources:
                limits:
                  memory: 2Gi
                requests:
                  memory: 500Mi
  
              env:
                - name: LOG_LEVEL
                  value: INFO
                - name: FLAME_TASK_ID
                  value: <% taskId %>
                - name: FLAME_TASK_KEY
                  value: <% taskKey %>
          restartPolicy: Never
    <%={{ }}=%>
