apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
    name: {{ .Release.Name }}-controller
    namespace: {{ .Release.Namespace }}
    {{- if .Values.ingress.annotations }}
    annotations:
      {{- range $key, $value := .Values.ingress.annotationsMlflow }}
      {{ $key }}: {{ tpl $value $ | quote }}
      {{- end }}
    {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.ingressClassName }}
    rules:
    - host: {{ .Values.frontDoorUrl.controller }}
      http:
        paths:
        {{ if eq .Values.ingress.apiVersion "networking.k8s.io/v1" }}
        - backend:
            service:
              name: {{ .Release.Name }}-controller
              port:
                number: 80
          pathType: Prefix
          path: /
        {{ else }}
        - backend:
            serviceName: {{ .Release.Name }}-controller
            servicePort: 80
          path: /
        {{ end }}
