---
# Source: flame/charts/mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flame-mongodb
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.31.3
    app.kubernetes.io/instance: flame
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: flame-mongodb
