apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-minio
spec:
  rules:
  - host: {{ .Values.frontDoorUrl.minio }}
    http:
      paths:
      - path: /
        backend:
          service:
            name:  {{ .Release.Name }}-minio
            port:
              number: {{ .Values.servicePort.minio }}
        pathType: Prefix